### ISSUE TITLE
Access the original object + some ideas

### ISSUE THREAD

**Issue by Stnaire** [gullerya/object-observer#110]
Hi,

First of all, thanks for the lib, it works great overall.

I have a special need though, I would like to access the **original object** being observed through the observable proxy.
More precisely, I need to access its **constructor** because I use it to index a metadata object in my app.

The way you do it make it impossible to access the original object from the proxy (or I missed something).

It is something you could add?

For now I modified the `prepareObject` method to define a new property:

```js
prepareObject = (source, oMeta) => {
    const target = Object.defineProperties({}, propertiesBluePrint);

    // Here the ugly change
    Object.defineProperty(target, '_ot', {
        configurable: false,
        enumerable: false,
        value: source
    });
    // End

    target[oMetaKey] = oMeta;
    for (const key in source) {
        target[key] = getObservedOf(source[key], key, oMeta);
    }
    return target;
}
```
But it's ugly, there may be a better way to do it.

----------

Also.. correct me if I'm wrong, but the way you define the `observe` and `unobserve` methods is dangerous, because if the observed object already defines methods with the same name, yours will be overridden and the object will not be observable at all.

Same thing for my `_ot` property, it could conflict with a property of the source object.

Wouldn't be better to hold some kind of map internally that will make the bridge between a list of subscribers and observed objects, so you can do something like:

```js
const proxy = Observable.proxify(model);
Observable.observe(proxy, () => [...]); // Here `observe` is more like a "subscribe" method
```
instead of:
```js
const observed = Observable.from(model);
observed.observe(() => [...]);
```

Thanks again for your work.

**Comment by gullerya** [comment]
Hi and thanks, to begin with!

I'll react on both points, while generally speaking I tend to keep the current state of things, sorry to be disappointing :)

A. Regarding the book-keeping of the `source` and `observable`:
- you are right, there is no backtracking to the source from the observable
- primary reason: once source is cloned to become observable there is no any guarantee on any content relation between those objects, beside the pointers themselves; it is for maximum unambiguity, so that there will be no expectations of any alignment between those 2 (mutation of observable are obviously not reflected in the source)
- I suggest that functionality like yours should lay in the consumer land:
  - either maintain a map of `source <> observable` - bit more logistics but error-proof
  - or create as part of the model some UUID, which will be present in the observable as well and do the book-keeping through this ID - this is classic, but should take care to not accidentally mutate the ID self
  - fully switch to use the observable, use it in itself as a reference in your index and drop the source away - not possible if the source is some class with some non-POJO logic (in this case I'd say that maybe it is better to separate the concerns of data and functionality...)

B. I indeed am not very happy about 'patching' the original object.
At some early point of project I've checked for presence of `observe` and `unobserve` on the source and if found - have thrown. Later decided to shave this off to save some nanos :)
Actually the internal map/list of the observables and subscribers already exists, so it is just a matter of changing the API.
Your suggestion looks good, to be honest (I'll definitely keep the `from` :) instead of `proxify` though).
I'll open a ticket to explore it and implement if feasible.
Obviously, the present 'patching` behavior will stay for at least 1 major version, since removing it will break things.

**Comment by gullerya** [comment]
@Stnaire FYI, the part of the non-polluting API as per your suggestion was implemented and available from `v4.8.0`.
The present behavior of patching the input with `observe` / `unobserve` methods will be removed only from `v5`, since it's a heavily breaking change.

**Comment by Stnaire** [comment]
Hey man, sorry for the late response.

Nice to see that you've already updated the lib, that was quick :)

About my main issue, I realized after reading your response that the issue is far deeper that I thought initially.

It may seem crazy but I didn't realize that the changes are not reflected on the source object before you said: `mutation of observable are obviously not reflected in the source`.
My use case of your lib is very niche in my tools and the fact that the source object is not altered is not obvious the way I use it for now.

But I need the source object to mutate. In fact it's very crutial for what I do with it.

Let me explain.

I'm building a lib for almost a year now (that I hope to release soon) in which you can sychronize a form with a model class.

The component that uses your lib is called `FormModelBinder` and does exactly what its name suggest, it reflects changes on a model into a form, and vice-versa.

So in order for it to work, I need to detect any change the user could make to the model. But the user may use the model for other things, could use functions inside etc. So the original instance must be preserved and modifiable.
Your way of doing the detection is in fact not compatible with my use case at all.

Consider the following example:

```ts
class User {
    public name: string = 'Paul';
}

const originalUser = new User();
const proxifiedUser = Observable.from(originalUser);

console.warn('Original state');
console.log('original', originalUser.name);
console.log('proxy', proxifiedUser.name);
console.log('');

// Modify the original object
originalUser.name = 'New name (original)';

console.warn('Modified state (original)');
console.log('original', originalUser.name);
console.log('proxy', proxifiedUser.name);
console.log('');

// Modify the proxy
proxifiedUser.name = 'New name (proxy)';

console.warn('Modified state (proxy)');
console.log('original', originalUser.name);
console.log('proxy', proxifiedUser.name);
```
Will give the following result:
![image](https://user-images.githubusercontent.com/8102092/153755257-4192301a-8fa6-4855-b93e-9766d75861fe.png)

Here I have two different objects, each with its own values.

What I need is something that takes an object and replace its properties by proxies.

This way the original object is fully functionnal, as it was before being observed and the constructor/prototype is preserved.

I don't expect you to update your lib for this, as it's a radically different approch that what you've done.

I'm thinking of writing my own basic utility to integrate directly in my lib, would it be ok for you if I grab some code here and there from yours? 
Of course any code I borrow will be commented to link to your project.

Or if you want to take part of its developpment or see to modify your lib you tell me.

I'm opened to discussion.

Cheers mate.

**Comment by gullerya** [comment]
:)
Of course NP, to take the code, you don't even need to mention it, just if you feel so.

I'd yet like to stress out few points of knowledge, that at least may help you to do your decisions:
- I found it confusing to pretend to preserve the original object and yet provide deep observation: think that if `user` has nested object `address`, than you'd like to proxify the `address` too, and then actually mutate the `user`, so that original `address` got replaces with the proxified one - thus some of the source is staying original and some gets replaced
- the fact that you tend to preserve the original object means that there is more than just POJO data there - this is anyway better to be avoided (subjective opinion, I know, but kinda common in SOA), and once you have separated the pure data and the logic - the pure data can become `Observable` and just become the 'source of truth'
- :) last but not least - I've also written some kind of binding framework, built on top of `object-observer` - [data-tier](https://www.npmjs.com/package/data-tier) - you may have take a look there

Regarding your intention and my last point: it was one of my primary milestones to understand that observation and DOM binding are separate concerns and deserves libs separation. So whatever you decide to do - better to keep a sharp API approach between those two.

Hope that helps!

**Comment by gullerya** [comment]
If this issue is resolved from your POV, please let's close it, thanks.

**Comment by Stnaire** [comment]
Yes sorry, thank you for your advice.
I'll let you know when I've done the rewrite, I didn't have time last week.
Cya :)
