### ISSUE TITLE
Unwrapping proxies, getting the original raw object

### ISSUE THREAD

**Issue by seahindeniz** [gullerya/object-observer#140]
Hello, is there a way to unproxy the observed object? Something like Vue's `toRaw` utility https://vuejs.org/api/reactivity-advanced.html#toraw

**Comment by gullerya** [comment]
Well, took some time :) but I've got to this one - indeed there is not formal API to get back to the original object.
I'd like to understand the use-case, due to 2 following concerns:
- original input is being deep-cloned during the make of the `Observable`, so the reference to to original object is anyway unpreserved (I consider that to be a consumer-land logic)
- unproxified object (graph) will destruct the `Observable`, and if to support otherwise - it'll potentially create a mess of split-brained objects, all similar, some observed some not etc

If the idea is at some point to (A) terminate the observation; and (B) get the raw object with the state as it is on that moment - looks like not a big issue, just would like to understand the what is it for.

**Comment by gullerya** [comment]
Closing as of no continuation of discussion. If interested - please reopen.
