### ISSUE TITLE
How To get the changed object ? 

### ISSUE THREAD

**Issue by Jarajesh** [gullerya/object-observer#24]
this is not a issue. But not sure where to ask so putting it up here.

Based on the example:

```
let order = { type: 'book', pid: 102, ammount: 5, remark: 'remove me' },
    observableOrder = Observable.from(order);

observableOrder.ammount = 7;
```

I need to submit observableOrder to the backend.
observableOrder should be
`{ type: 'book', pid: 102, ammount: 7, remark: 'remove me' }`

But when I
 `
console.log(observableOrder);`
I get the following

```
Proxy {amount: 7, pid: 102, type: "book", address: Proxy, revoke: ƒ, …}
[[Handler]]: ObjectObserver
isRevoked: false
proxy: Proxy {amount: 7, pid: 102, type: "book", address: Proxy, revoke: ƒ, …}
revokable: {proxy: Proxy, revoke: ƒ}
target: {amount: 7, pid: 102, type: "book", address: Proxy, revoke: ƒ, …}
observers: Map(1) {ƒ => {…}}
__proto__: ObserverBase
[[Target]]: Object
address: Proxy {apt: 30, street: "Str 75", Symbol(system-observer-key): ObjectObserver}
amount: 7
pid: 102
type: "book"
Symbol(system-observer-key): ObjectObserver {isRevoked: false, revokable: {…}, proxy: Proxy, target: {…}, observers: Map(1)}
observe: ƒ value(observer, options)
revoke: ƒ value()
unobserve: ƒ value()
__proto__: Object
[[IsRevoked]]: false
```

How Can I get the original value back without the attached properties?

**Comment by gullerya** [comment]
Hi,
First of all, thanks for an interest and for the questions.
Regarding the question self - there is **no** API to get back the 'stripped' yet up-to-date object, and I believe it is **not needed**:
* all of the 'internal' library's properties are not iterable, some of them even `Symbol`'s, so it should not influence any of your logic when, say, iterating over the `Observable` version of object
* due to the said above, `JSON.stringify`, for instance, will also perfectly skip all those internals and will bring you only the relevant data serialized
* regardless, I would consider it best practice to actually copy/clone the data when, let's call it, moving it from context to context (in your example, from UI/data binding/client side local logic via serialization to the server)

I've updated the JSFiddle (the one that was broken and now is fixed :)) with few examples related to this question, you may like to take a look on that.

**Comment by gullerya** [comment]
Closing since looks like the answers were sufficient here and in another issue thread, please reopen if relevant or submit new issue.
