### ISSUE TITLE
Prototype chain preservation

### ISSUE THREAD

**Issue by kilame** [gullerya/object-observer#30]
Hi,

I'm using your library with minor tweak. I've added support for prototype chain preservation.

Solution is simple. Add `target.__proto__ = source.__proto__;` on line 100.

**Comment by gullerya** [comment]
Hi,

Glad to hear it's useful, thanks.

About that tweak: I'm not a big fan of `__proto__` to say it modestly, it is language internals and it's usage is [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto).

Yet, there is an `Object.create()` alternative. I've not considered that yet since had no such a use-case. Can you tell me shortly your case please, or, even better, some short snippet of test case for that?

**Comment by gullerya** [comment]
Well, I've not really found so far some good reason to support "upper" chain.
Moreover, I think that although it is possible even now to create observable from an object which is part of a bigger graph, it looks to me like some design flaw to play with it like this.
Anyway - if there will emerge some reasoning/examples to add this functionality, please reopen this issue and we'll start the conversation over again.
