### ISSUE TITLE
Can I copy the payload in the change handler?

### ISSUE THREAD

**Issue by bbsimonbb** [gullerya/object-observer#90]
This could be a newbie problem or a feature request: (How) Can I recover the original object in the change handler each time it changes? When notified of a change on my observed object, I want to create a copy (of the original object) with just the original properties. Is this possible? I see I've got observableObject.unobserve(), but I don't want to unobserve. I just want to make a copy of the target.

[This could be what I'm looking for](https://stackoverflow.com/questions/47216091/retrieve-original-target-object-from-existing-proxy-instance)? Is this the best approach?

**Comment by gullerya** [comment]
Hi, thanks for question and sorry for delay.

I'd consider it a general task that you probably would like to code yourself, since it it not something that `object-observer` intended to do.

Indeed, `OO` holds in some internal structure the original refs to the whole observed tree, and indeed upon `unobserve` it reconstructs the whole tree again, but that would be an expensive operation to do upon each change and I'd like to keep it as faster as possible upon changes delivery.

Can you probably explain me the use case, why would you like to obtain the underlying 'raw' data instead of just working with `Observable` self?

**Comment by bbsimonbb** [comment]
My use case: I want my observable structure to "publish" a read-only copy. I've implemented an acyclic graph, where each node in the graph has an observable outputValue. These will likely be small objects, but there are potentially lots of them. When a node changes its outputValue, the graph structure publishes a read only copy (of the outputValue), then triggers a recalculation on all downstream nodes.

I have a working prototype, but I'm not at all sure  I'm solidly on the right track yet. The ambition is a rules engine/state management solution for Vue, nothing less!

**Comment by gullerya** [comment]
The use case is rather complex, so I'll probably be off the line.

If I'm getting right, that graph is a state as a whole.
That alone could be achieved with the `OO` alone, meaning:
- the graph is turned into `Observable` as a whole
- any change somewhere in the graph can be observed (via single observer, or multiples observers, per paths or some other custom logic)
- upon any change relevant changes to the Vue's model applied
- but you probably do not want to just put the `Observable` pointer into Vue's model, since it'll become mutable from the other end
- also you probably would like to apply some rules to calculate some of the other graph's values

If till now we are on the same page - I'd say that you'll need to pull some utility or write your own deep clone as of now. So that upon each change, you copy the `Observable` into a new raw graph and work with this one.
Another suggestion would be - why not just use the `Observable` as is, giving it as a Vue's model refs, and just put the observers for those special rules logic?

I can think of API, that'll bring the underlying raw (sub)-graph of the given `Observable`, without unobserving it. The only concern I have, is that you as a consumer (generally speaking, when saying 'you', of course) may end up confused, mutating that underlying data, not getting observation notifications on the other end etc.

**Comment by gullerya** [comment]
Closing for the lack of conversation continuation, feel free to open again if needed.

**Comment by bbsimonbb** [comment]
Thanks for your input. With your suggestions I got something working. I'll come back if I have a more precise requirement. Great package, thanks for your work.
