### ISSUE TITLE
Unable to get regexp from observable

### ISSUE THREAD

**Issue by K0nfy** [gullerya/object-observer#96]
**Code:**
```js
import { Observable } from 'https://libs.gullerya.com/object-observer/4.5.0/object-observer.js';

const obj = { regex: new RegExp('foo') };
const obs = Observable.from(obj);

console.log(obs.regex);
console.log(obs.regex.exec);
```
or [CodePen](https://codepen.io/Konf/pen/KKvrJPX?editors=0010).

**Expected behavior:**
Regexp instance or its method are logged in console (and can be used)

**Current behavior:**
`obs.regex` returns `Proxy` and `obs.regex.exec` returns `undefined`
<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/27099419/141969158-4485cffd-392e-4654-a6a6-44f35712d321.png">
</details>

**Possibly related:**
https://github.com/gullerya/object-observer/issues/2

**Comment by gullerya** [comment]
I have a use-case question to just a grasp it, since what happened to me along the time, that I've struggled to find a real use-cases for all those excluded natives and eventually removed most of them from curing.

The concern is the performance - the more those native excludes we have, it'll impact lineary (On) the performance of creation of the observable.

So having this - is it a real use case to have RegExps in the observable data set? I've basically thought that observation makes most of the sense on some pretty POJO data bags. Can you please share a bit with the case that you have? Don't you think that down the road you'll take those 'living' objects like RegExps out of the observable data set?

Thanks.

**Comment by K0nfy** [comment]
My use case is: a little nodejs express server with [lowdb](https://www.npmjs.com/package/lowdb) that saves my little global storage object into json and I decided to make this object observable to save the db on every change event of the object. A few regexps that I'm saving are used as parsers of express route and user input, and they could be changed in future (rarely configurable variables) so I just wanted to keep all configurables in one place. 

Since that's pretty much it, I can just move them somewhere else or make conversions like this:
```js
/foobar/im -> { body: foobar, flags: 'im' }
```

**Comment by gullerya** [comment]
So when the storage, including the regexps, is saved into that DB and then dumped into the file, how the regexps are serialized? Don't you loose them there as well?

**Comment by K0nfy** [comment]
You mean save without `object-observer`? **\*went and checked\*** Yes, I do lose. `lowdb` saves regexps as empty objects

So plain data approach is the right way in my use case anyway

**Comment by gullerya** [comment]
Great, thanks!
I presume then, that as of now there is still no need for curing the native objects.
I'll update the #2 issue as well.
